import type { Lesson } from '../api'

export const lessonFixture: Lesson = {
  slug: 'lesson-one', quality_status: 'reviewed', title_vi: 'Kiểm tra Python', title_en: 'Check Python',
  summary_vi: 'Xác định Python đang chạy.', summary_en: 'Identify the running Python interpreter.',
  objectives: { vi: ['Đọc phiên bản'], en: ['Read the version'] },
  learning_objectives: { vi: ['Đọc phiên bản'], en: ['Read the version'] },
  prerequisites: ['earlier-lesson'], keywords: ['Python'], concept_notes_vi: 'Dùng sys.version.',
  concept_notes_en: 'Use sys.version.', formulas: [], code_examples: [{ language: 'python',
    title: 'Version', code: 'import sys\nprint(sys.version)', explanation_vi: 'In phiên bản Python.',
    explanation_en: 'Print the Python version.', status: 'runnable' }],
  resources: [{ title: 'Python docs', url: 'https://docs.python.org/3/', language: 'en', kind: 'official',
    purpose_vi: 'Đọc về Python.', purpose_en: 'Read about Python.', read_vi: 'Xem phiên bản.', read_en: 'Check the version.' }],
  checklist: ['Chạy Python', 'Giải thích output'], completion_checklist: ['Chạy Python', 'Giải thích output'],
  completion_checklist_en: ['Run Python', 'Explain the output'],
  completion_criteria: ['Chạy không lỗi'], completion_criteria_en: ['Run without errors'],
  common_mistakes: ['Dùng nhầm interpreter'], common_mistakes_en: ['Using the wrong interpreter'],
  next_lessons: ['next-lesson'], exercise_ids: ['exercise-0-environment'], review_item_ids: [1],
  estimated_minutes: 30, status: 'not_started', minutes_spent: 0,
  phase_title_vi: 'Bắt đầu', phase_title_en: 'Getting started', module_title_vi: 'Môi trường',
  module_title_en: 'Environment', reviews: [{ id: 1, question_vi: 'Đọc phiên bản ở đâu?',
    question_en: 'Where is the version?', answer_vi: 'Trong sys.version.', answer_en: 'In sys.version.' }],
  exercises: [{ id: 1, slug: 'exercise-0-environment', title_vi: 'Kiểm tra Python đang chạy',
    title_en: 'Inspect the Python environment', description_vi: 'Kiểm tra môi trường.',
    description_en: 'Inspect the environment.', difficulty: 'starter', estimated_minutes: 30,
    test_command: 'python -m unittest', hints: [] }],
  why_it_matters_vi: 'Biết môi trường của bạn.', why_it_matters_en: 'Know your environment.',
  study_steps_vi: ['Nắm ý chính', 'Đọc', 'Chạy', 'Lưu bằng chứng', 'Tự nhớ lại'],
  study_steps_en: ['Understand', 'Read', 'Run', 'Save evidence', 'Recall'],
  practice_plan: { vi: { task: 'Chạy ví dụ', deliverables: ['Output'], checkpoint: 'Đọc được phiên bản' },
    en: { task: 'Run the example', deliverables: ['Output'], checkpoint: 'Read the version' } },
  interview_questions: { vi: ['Vì sao dùng venv?'], en: ['Why use a venv?'] },
}
