import { expect, test } from '@playwright/test'
import { checkThemeContrast } from './theme-checks'

for (const language of ['vi', 'en'] as const) {
  test(`${language} mobile navigation contains focus and returns to the selected page`, async ({ page }) => {
    const vi = language === 'vi'
    await page.route('**/api/settings', async (route) => {
      const response = await route.fetch()
      await route.fulfill({ json: { ...await response.json(), language } })
    })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/')
    await expect(page.locator('.today-next')).toBeVisible()
    const menu = page.locator('.sidebar')
    const trigger = page.getByRole('button', { name: vi ? 'Mở menu điều hướng' : 'Open navigation' })
    await expect(menu).not.toBeVisible()
    // Hidden navigation must not accept focus, even when targeted programmatically.
    await menu.locator('.nav-item').first().evaluate((button: HTMLButtonElement) => button.focus())
    await expect(menu.locator('.nav-item').first()).not.toBeFocused()
    await trigger.focus()
    await page.keyboard.press('Enter')
    await expect(menu).toHaveAttribute('role', 'dialog')
    await expect(menu).toHaveAttribute('aria-modal', 'true')
    const close = menu.getByRole('button', { name: vi ? 'Đóng menu điều hướng' : 'Close navigation' })
    await expect(close).toBeFocused()
    await expect(page.locator('main')).toHaveAttribute('inert', '')
    expect(await page.evaluate(() => document.body.style.overflow)).toBe('hidden')
    await page.keyboard.press('Shift+Tab')
    await expect(menu.locator('.nav-item').last()).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(close).toBeFocused()
    await page.keyboard.press('Control+k')
    await expect(close).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(menu).not.toBeVisible()
    await expect(trigger).toBeFocused()
    await expect(page.locator('main')).not.toHaveAttribute('inert', '')
    expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
    await trigger.click()
    await menu.getByRole('button', { name: vi ? 'Bài tập Mở bằng VS Code' : 'Exercises Practice in VS Code' }).click()
    await expect(page).toHaveURL(/\/exercises$/)
    await expect(menu).not.toBeVisible()
    await expect(page.locator('main')).toBeFocused()
    await expect(page.locator('.practice-list')).toBeVisible()
    await trigger.click()
    await page.locator('.mobile-nav-scrim').click({ position: { x: 350, y: 400 } })
    await expect(trigger).toBeFocused()
    await expect(menu).not.toBeVisible()
    await trigger.click()
    await page.goBack()
    await expect(page).toHaveURL(/\/$/)
    await expect(menu).not.toBeVisible()
    await expect(page.locator('main')).toBeFocused()
    for (const width of [320, 390, 820]) {
      await page.setViewportSize({ width, height: 700 })
      for (const theme of ['light', 'dark'] as const) {
        await page.emulateMedia({ colorScheme: theme, reducedMotion: 'reduce' })
        await trigger.click()
        await expect(close).toBeFocused()
        await checkThemeContrast(page)
        const box = await close.boundingBox()
        expect(box!.width).toBeGreaterThanOrEqual(44)
        expect(box!.height).toBeGreaterThanOrEqual(44)
        await menu.locator('.nav-item').last().focus()
        await expect(menu.locator('.nav-item').last()).toBeInViewport()
        await close.focus()
        await page.screenshot({ path: `.build/navigation-evidence/${language}-${theme}-${width}.png` })
        await page.keyboard.press('Escape')
      }
    }
    await trigger.click()
    await page.setViewportSize({ width: 1440, height: 900 })
    await expect(menu).toBeVisible()
    await expect(menu).not.toHaveAttribute('aria-modal', 'true')
    await expect(menu.locator('[aria-current="page"]')).toBeFocused()
    await expect(page.locator('main')).not.toHaveAttribute('inert', '')
    expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
    await checkThemeContrast(page)
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(menu).not.toBeVisible()
    await expect(trigger).toBeFocused()
    await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  })
}
