import type { GuideText } from './exercise-guides'

export const foundationGuides: Record<string, Record<'vi' | 'en', GuideText>> = {
  'exercise-1-python-core': {
    vi: {
      summary: 'Tạo gói Python tính điểm có trọng số: viết hàm thuần, khai báo kiểu dữ liệu, kiểm tra đầu vào và thử các trường hợp biên.',
      steps: [
        'Xét bài toán nhỏ: weighted_score(items) nhận danh sách các tuple (điểm, trọng số). Điểm thuộc [0,100], trọng số thuộc (0,1]; cần chuẩn hóa tổng trọng số trước khi tính trung bình.',
        'Tạo thư mục study_scores với tệp __init__.py bên trong. Viết hàm có chú thích kiểu (type hint). Hàm không in kết quả, không đọc tệp và không sửa danh sách đầu vào.',
        'Báo ValueError cho danh sách rỗng, sai cấu trúc, bool, chuỗi, NaN hoặc số ngoài khoảng. Kiểm tra các điều kiện này trước bước tính toán.',
        'Đặt test_solution.py bên cạnh thư mục gói. Kiểm thử ví dụ thông thường, trọng số không có tổng bằng 1, điểm 0/100, đầu vào sai và việc giữ nguyên đầu vào.',
        'Chạy python -m unittest -v test_solution.py. Giải thích vì sao chú thích kiểu không thay thế việc kiểm tra đầu vào khi chạy.',
      ],
      checks: ['[(80,0.25),(100,0.75)] → 95; [(0,0.2),(100,0.2)] → 50.',
        'Danh sách rỗng, bool và NaN phải báo lỗi; đầu vào không bị sửa.',
        'Khi thêm yêu cầu mới, viết kiểm thử trước rồi tự sửa hàm, không chép lại đáp án.'],
      hints: ['Tổng có trọng số cần chia cho tổng trọng số.', 'Dùng assertAlmostEqual cho số thực.'],
      example: 'weighted_score([(80, 0.25), (100, 0.75)])  # 95\nweighted_score([(0, 0.2), (100, 0.2)])  # 50',
    },
    en: {
      summary: 'Build a weighted-score package with a pure function, type hints, validation and edge-case tests.',
      steps: [
        'Choose a small task: weighted_score(items) accepts a list of (score, weight) tuples. Scores are in [0,100], weights in (0,1]; normalize by the total weight.',
        'Create study_scores/__init__.py. Write a type-hinted function without printing, file reads or input mutation.',
        'Raise ValueError for empty lists, wrong structure, bools, strings, NaN or out-of-range values before calculating.',
        'Place test_solution.py next to the package. Cover normal inputs, weights not summing to 1, boundary scores, bad inputs and input preservation.',
        'Run python -m unittest -v test_solution.py. Explain why type hints do not replace runtime validation.',
      ],
      checks: ['[(80,0.25),(100,0.75)] → 95; [(0,0.2),(100,0.2)] → 50.',
        'Empty lists, bools and NaN raise errors; inputs remain unchanged.',
        'Add a new requirement by writing a test first, then changing the function without copying the answer.'],
      hints: ['Divide the weighted sum by the total weight.', 'Use assertAlmostEqual for floating-point results.'],
      example: 'weighted_score([(80, 0.25), (100, 0.75)])  # 95\nweighted_score([(0, 0.2), (100, 0.2)])  # 50',
    },
  },
  'exercise-1-reliable-code': {
    vi: {
      summary: 'Tái hiện lỗi do dùng chung danh sách mặc định, tìm nguyên nhân qua nhật ký chạy và viết kiểm thử hồi quy để lỗi không xuất hiện lại.',
      steps: [
        'Viết phiên bản cố ý lỗi ở ví dụ bên dưới. Dự đoán hai kết quả trước khi chạy; ghi lại kết quả thực tế.',
        'Ghi giả thuyết rằng hai lần gọi dùng chung danh sách. In id(tags) và nội dung tags trước/sau append, hoặc đặt điểm dừng gỡ lỗi tại đó.',
        'Viết kiểm thử gọi add_tag hai lần không truyền tags và yêu cầu hai danh sách độc lập. Chạy kiểm thử với mã lỗi để thấy FAIL.',
        'Sửa giá trị mặc định thành None, tạo danh sách mới hoặc sao chép danh sách truyền vào. Từ chối tag rỗng, cắt khoảng trắng ở hai đầu và không thêm tag đã có.',
        'Chạy lại kiểm thử hồi quy, thêm trường hợp đầu vào sai và kiểm tra danh sách truyền vào không bị sửa. Ghi rõ cách phân biệt lỗi đầu vào, lỗi logic và lỗi môi trường.',
      ],
      checks: ['Hai lần gọi lần lượt trả ["python"] và ["sql"], không chia sẻ trạng thái.',
        'Kiểm thử hồi quy phải thất bại ở phiên bản lỗi và thành công ở phiên bản sửa.',
        'Có nhật ký hoặc quan sát hỗ trợ giả thuyết; giải thích được kiểm thử nào ngăn lỗi cũ quay lại.'],
      hints: ['Giá trị mặc định được tạo khi định nghĩa hàm.', 'Thử kiểm tra first is second và id(tags).'],
      example: '# Code cố ý có lỗi để điều tra\ndef add_tag(tag, tags=[]):\n    tags.append(tag)\n    return tags\n\nfirst = add_tag("python")\nsecond = add_tag("sql")\nprint(first, second)',
    },
    en: {
      summary: 'Reproduce a shared-default-list bug, investigate it with logs and protect the fix with a regression test.',
      steps: [
        'Write the intentionally broken example below. Predict both results before running it; record the actual output.',
        'Hypothesize that the calls share one list. Log id(tags) and its contents before/after append, or set a breakpoint there.',
        'Write a test calling add_tag twice without supplying tags and requiring independent lists. Run it against the bug and observe FAIL.',
        'Use None as the default, creating or copying a list. Reject empty tags, trim surrounding spaces and skip existing tags.',
        'Rerun the regression test; add invalid-input and input-preservation tests. Distinguish input, logic and environment failures.',
      ],
      checks: ['The calls return ["python"] and ["sql"] independently.',
        'The regression test fails before the fix and passes afterwards.',
        'Logs or debugger observations support the hypothesis; identify the test that prevents recurrence.'],
      hints: ['Default values are created when the function is defined.', 'Inspect first is second and id(tags).'],
      example: '# Intentionally broken code to investigate\ndef add_tag(tag, tags=[]):\n    tags.append(tag)\n    return tags\n\nfirst = add_tag("python")\nsecond = add_tag("sql")\nprint(first, second)',
    },
  },
  'exercise-1-data-files': {
    vi: {
      summary: 'Làm sạch CSV thành JSON, giữ điểm 0 và báo số dòng cùng lý do cho dữ liệu không hợp lệ.',
      steps: [
        'Tạo scores.csv như ví dụ. Yêu cầu dòng tên cột đúng name,score; cắt khoảng trắng ở hai đầu tên; điểm là số hữu hạn thuộc [0,100]. Không đoán giá trị thiếu.',
        'Dùng csv.DictReader để đọc UTF-8 và kiểm tra dòng tên cột trước khi xử lý từng bản ghi. Sai tên cột thì dừng; dòng dữ liệu sai được ghi vào errors.',
        'Tách records và errors. Với mỗi lỗi, lưu số dòng vật lý cuối của bản ghi và lý do. Giữ điểm 0; báo lỗi cho NaN, tên rỗng hoặc sai số cột.',
        'Thêm giao diện dòng lệnh (CLI) nhận đường dẫn nguồn và đích. Ghi JSON hợp lệ, không sửa nguồn. Chạy lại cùng đầu vào phải cho cùng kết quả, không nối thêm vào tệp.',
        'Kiểm thử tên cột sai, điểm biên, dòng thiếu/thừa cột và CSV có dấu phẩy trong tên. Chạy kiểm thử và quy trình xử lý từ cửa sổ dòng lệnh, đọc cả records lẫn errors.',
      ],
      checks: ['Ví dụ tạo hai bản ghi: An=0, Bình=90; lỗi invalid_score ở dòng 4.',
        'Chạy lại không nhân đôi bản ghi và không đổi tệp nguồn.',
        'Giải thích được vì sao cần cắt khoảng trắng ở tên, giữ điểm 0, loại NaN và không tự điền điểm thiếu.'],
      hints: ['Không tách CSV bằng split(",").', 'float có thể tạo NaN hoặc giá trị vô hạn; cần kiểm tra bằng math.isfinite.'],
      example: '# scores.csv (lưu từ dòng name,score, không lưu dòng chú thích này)\nname,score\n An ,0\nBình,90\nBad,NaN',
    },
    en: {
      summary: 'Clean CSV into JSON, preserve zero scores and report line numbers with reasons for invalid data.',
      steps: [
        'Create scores.csv using the example. Require the name,score header; trim names; accept finite scores in [0,100]. Do not invent missing values.',
        'Read UTF-8 with csv.DictReader and validate the header first. A bad header stops processing; bad data rows go to errors.',
        'Separate records and errors. Each error includes the record’s ending physical line and reason. Preserve zero; reject NaN, empty names and wrong column counts.',
        'Add a CLI accepting source and destination paths. Write valid JSON without changing the source; repeating the run must not append records.',
        'Test bad headers, boundary scores, short/long rows and quoted commas in names. Run tests and the pipeline in a terminal; inspect records and errors.',
      ],
      checks: ['The example produces two records: An=0 and Bình=90, plus invalid_score at line 4.',
        'Rerunning neither duplicates records nor changes the source.',
        'Explain each policy: trim names deliberately, preserve zero, reject NaN and never invent missing scores.'],
      hints: ['Do not parse CSV with split(",").', 'float accepts NaN and infinity: check math.isfinite.'],
      example: '# scores.csv (save starting at name,score; omit this comment)\nname,score\n An ,0\nBình,90\nBad,NaN',
    },
  },
}
