export const journalCopy = {
  vi: {
    heading: 'Hành trình của bạn', synced: 'được đồng bộ.', local: 'nằm trong Git.',
    introCloud: 'Notes và journal được đồng bộ theo tài khoản. Dùng source clone để review diff và commit GitHub.',
    introLocal: 'Export journal mỗi tuần, review diff trước khi commit và ghi lại câu chuyện kỹ thuật của bạn.',
    weekly: 'Journal tuần',
    exportCloud: 'Tải journal dạng Markdown. Tiến độ và notes được đồng bộ riêng theo tài khoản.',
    exportLocal: 'Journal được ghi vào journal/weekly, sẵn sàng để bạn review trước khi chia sẻ lên GitHub.',
    exporting: 'Đang xuất…', export: 'Xuất journal →', created: 'Đã tạo',
    ask: 'Hỏi ChatGPT / Codex', noKey: 'Không cần API key',
    contextInfo: 'App tạo context gồm lesson, tiến độ, note và nguyên tắc học để bạn dán sang trợ lý.',
    question: 'Câu hỏi cho trợ lý', questionHint: 'Ví dụ: Vì sao validation loss của tôi tăng?',
    defaultQuestion: 'Hãy giúp tôi hiểu phần này bằng gợi ý từng bước.',
    creating: 'Đang tạo…', create: 'Tạo context & copy', context: 'Context vừa tạo',
    copied: 'Đã copy ✓', copy: 'Copy lại', savedAt: 'Đã lưu:',
    clipboardError: 'Không truy cập được clipboard. Chọn nội dung trong ô context rồi sao chép thủ công.',
    contextError: 'Không tạo được context. Hãy thử lại.',
    exportError: 'Không xuất được journal. Hãy thử lại.',
    loadError: 'Không tải được Journal hoặc Git snapshot.',
    notes: 'Insight đã lưu', refresh: 'Làm mới', loading: 'Đang tải…', general: 'Ghi chú chung',
    empty: 'Chưa có note. Mở một lesson và ghi lại điều bạn tự phát hiện.',
    branch: 'Nhánh', lastCommit: 'Commit gần nhất', remote: 'Remote',
    noBranch: 'Chưa khởi tạo', noCommit: 'Chưa có commit', noRemote: 'Chưa cấu hình',
    gitLoading: 'Đang đọc trạng thái Git…', gitUnavailable: 'Chưa tải được trạng thái Git.',
    suggested: 'Commit gợi ý:', clean: 'Working tree sạch hoặc chưa được khởi tạo.',
    diff: 'Xem diff đã che secret', noDiff: 'Chưa có diff.',
    cloudTitle: 'Reflection đồng bộ', private: 'Riêng tư',
    cloudInfo: 'Mỗi tuần có một reflection, được lưu riêng theo tài khoản của bạn.',
    week: 'Tuần bắt đầu', title: 'Tiêu đề', reflection: 'Reflection',
    reflectionHint: 'Điều đã hiểu, lỗi đã gặp, bằng chứng đã tạo và việc sẽ làm tiếp theo…',
    syncing: 'Đang đồng bộ…', save: 'Lưu reflection', saved: 'Đã đồng bộ journal.',
    required: 'Hãy ghi tiêu đề và nội dung reflection trước khi lưu.',
    saveError: 'Không lưu được journal. Hãy thử lại.',
    entries: 'reflection đã lưu', weekFrom: 'Tuần từ',
  },
  en: {
    heading: 'Your learning journey', synced: 'stays in sync.', local: 'lives in Git.',
    introCloud: 'Notes and journals sync to your account. Use a source workspace to review diffs and commit to GitHub.',
    introLocal: 'Export your journal each week, review the diff before committing and record your technical progress.',
    weekly: 'Weekly journal',
    exportCloud: 'Download your journal as Markdown. Progress and notes sync separately to your account.',
    exportLocal: 'Journals are saved in journal/weekly, ready for review before sharing on GitHub.',
    exporting: 'Exporting…', export: 'Export journal →', created: 'Created',
    ask: 'Ask ChatGPT / Codex', noKey: 'No API key',
    contextInfo: 'Create context with lessons, progress, notes and learning guidelines to paste into your assistant.',
    question: 'Question for your assistant', questionHint: 'For example: Why is my validation loss increasing?',
    defaultQuestion: 'Help me understand this topic with step-by-step hints.',
    creating: 'Creating…', create: 'Create context & copy', context: 'Generated context',
    copied: 'Copied ✓', copy: 'Copy again', savedAt: 'Saved:',
    clipboardError: 'Clipboard is unavailable. Select the text in the context box and copy it manually.',
    contextError: 'Could not create context. Please try again.',
    exportError: 'Could not export the journal. Please try again.',
    loadError: 'Could not load the journal or Git snapshot.',
    notes: 'Saved insights', refresh: 'Refresh', loading: 'Loading…', general: 'General note',
    empty: 'No notes yet. Open a lesson and record something you discovered.',
    branch: 'Branch', lastCommit: 'Last commit', remote: 'Remote',
    noBranch: 'Not initialized', noCommit: 'No commits yet', noRemote: 'Not configured',
    gitLoading: 'Reading Git status…', gitUnavailable: 'Git status is unavailable.',
    suggested: 'Suggested commit:', clean: 'Working tree is clean or not initialized.',
    diff: 'View diff with secrets redacted', noDiff: 'No changes to show.',
    cloudTitle: 'Synced reflection', private: 'Private',
    cloudInfo: 'Save one reflection per week, privately in your account.',
    week: 'Week starting', title: 'Title', reflection: 'Reflection',
    reflectionHint: 'What you learned, errors you met, evidence you created and what comes next…',
    syncing: 'Syncing…', save: 'Save reflection', saved: 'Journal synced.',
    required: 'Enter a title and reflection before saving.',
    saveError: 'Could not save the journal. Please try again.',
    entries: 'saved reflections', weekFrom: 'Week starting',
  },
}
