export const journalCopy = {
  vi: {
    heading: 'Nhật ký học tập', synced: 'lưu theo tài khoản.', local: 'lưu trên máy của bạn.',
    introCloud: 'Ghi chú và nhật ký được lưu theo tài khoản. Nếu muốn chia sẻ lên GitHub, hãy xuất nội dung và xem lại trước khi đăng.',
    introLocal: 'Mỗi tuần, ghi lại điều đã học và xuất nhật ký. Xem lại thay đổi trước khi lưu vào Git hoặc chia sẻ.',
    weekly: 'Nhật ký tuần',
    exportCloud: 'Tải nhật ký dưới dạng Markdown. Tiến độ và ghi chú được đồng bộ riêng theo tài khoản.',
    exportLocal: 'Nhật ký được lưu vào journal/weekly. Bạn hãy đọc lại trước khi chia sẻ lên GitHub.',
    exporting: 'Đang xuất…', export: 'Xuất nhật ký →', created: 'Đã tạo',
    ask: 'Hỏi ChatGPT / Codex', noKey: 'Không cần khóa API',
    contextInfo: 'Ứng dụng gom thông tin về bài học, tiến độ, ghi chú và nguyên tắc học để bạn gửi cho trợ lý. Đọc lại nội dung trước khi gửi.',
    question: 'Câu hỏi cho trợ lý', questionHint: 'Ví dụ: Vì sao hàm mất mát trên tập kiểm định (validation loss) tăng?',
    defaultQuestion: 'Hãy giúp tôi hiểu phần này bằng gợi ý từng bước.',
    creating: 'Đang tạo…', create: 'Tạo và sao chép nội dung', context: 'Nội dung gửi cho trợ lý',
    copied: 'Đã sao chép ✓', copy: 'Sao chép lại', savedAt: 'Đã lưu:',
    clipboardError: 'Không sao chép tự động được. Chọn nội dung trong ô bên dưới rồi sao chép thủ công.',
    contextError: 'Không tạo được nội dung gửi cho trợ lý. Hãy thử lại.',
    exportError: 'Không xuất được nhật ký. Hãy thử lại.',
    loadError: 'Không tải được nhật ký hoặc trạng thái Git.',
    notes: 'Ghi chú đã lưu', refresh: 'Làm mới', loading: 'Đang tải…', general: 'Ghi chú chung',
    empty: 'Bạn chưa có ghi chú. Mở một bài học và ghi lại điều vừa hiểu hoặc câu hỏi còn vướng.',
    branch: 'Nhánh', lastCommit: 'Commit gần nhất', remote: 'Kho từ xa',
    noBranch: 'Chưa khởi tạo', noCommit: 'Chưa có commit', noRemote: 'Chưa cấu hình',
    gitLoading: 'Đang đọc trạng thái Git…', gitUnavailable: 'Chưa tải được trạng thái Git.',
    suggested: 'Thông điệp commit gợi ý:', clean: 'Không có thay đổi chưa đưa vào commit hoặc chưa khởi tạo Git.',
    diff: 'Xem thay đổi đã che thông tin bí mật', noDiff: 'Chưa có thay đổi để hiển thị.',
    cloudTitle: 'Nhìn lại tuần học', private: 'Riêng tư',
    cloudInfo: 'Ghi lại một bài tổng kết mỗi tuần. Nội dung được lưu riêng trong tài khoản của bạn.',
    week: 'Tuần bắt đầu', title: 'Tiêu đề', reflection: 'Nội dung tổng kết',
    reflectionHint: 'Điều đã hiểu, lỗi đã gặp, bằng chứng đã tạo và việc sẽ làm tiếp theo…',
    syncing: 'Đang đồng bộ…', save: 'Lưu tổng kết', saved: 'Đã đồng bộ nhật ký.',
    required: 'Hãy ghi tiêu đề và nội dung tổng kết trước khi lưu.',
    saveError: 'Không lưu được nhật ký. Hãy thử lại.',
    entries: 'bài tổng kết đã lưu', weekFrom: 'Tuần từ',
  },
  en: {
    heading: 'Your learning journey', synced: 'stays in sync.', local: 'lives in Git.',
    introCloud: 'Notes and journals sync to your account. Use a source workspace to review diffs and commit to GitHub.',
    introLocal: 'Export your journal each week, review the diff before committing and record your technical progress.',
    weekly: 'Weekly journal',
    exportCloud: 'Download your journal as Markdown. Progress and notes sync separately to your account.',
    exportLocal: 'Journals are saved in journal/weekly, ready for review before sharing on GitHub.',
    exporting: 'Exporting…', export: 'Export journal →', created: 'Created',
    ask: 'Ask ChatGPT / Codex', noKey: 'No API key',
    contextInfo: 'Create context with lessons, progress, notes and learning guidelines to paste into your assistant.',
    question: 'Question for your assistant', questionHint: 'For example: Why is my validation loss increasing?',
    defaultQuestion: 'Help me understand this topic with step-by-step hints.',
    creating: 'Creating…', create: 'Create context & copy', context: 'Generated context',
    copied: 'Copied ✓', copy: 'Copy again', savedAt: 'Saved:',
    clipboardError: 'Clipboard is unavailable. Select the text in the context box and copy it manually.',
    contextError: 'Could not create context. Please try again.',
    exportError: 'Could not export the journal. Please try again.',
    loadError: 'Could not load the journal or Git snapshot.',
    notes: 'Saved insights', refresh: 'Refresh', loading: 'Loading…', general: 'General note',
    empty: 'No notes yet. Open a lesson and record something you discovered.',
    branch: 'Branch', lastCommit: 'Last commit', remote: 'Remote',
    noBranch: 'Not initialized', noCommit: 'No commits yet', noRemote: 'Not configured',
    gitLoading: 'Reading Git status…', gitUnavailable: 'Git status is unavailable.',
    suggested: 'Suggested commit:', clean: 'Working tree is clean or not initialized.',
    diff: 'View diff with secrets redacted', noDiff: 'No changes to show.',
    cloudTitle: 'Synced reflection', private: 'Private',
    cloudInfo: 'Save one reflection per week, privately in your account.',
    week: 'Week starting', title: 'Title', reflection: 'Reflection',
    reflectionHint: 'What you learned, errors you met, evidence you created and what comes next…',
    syncing: 'Syncing…', save: 'Save reflection', saved: 'Journal synced.',
    required: 'Enter a title and reflection before saving.',
    saveError: 'Could not save the journal. Please try again.',
    entries: 'saved reflections', weekFrom: 'Week starting',
  },
}
