import type { GuideText } from './exercise-guides'

export const mathGuides: Record<string, Record<'vi' | 'en', GuideText>> = {
  'exercise-2-linear-algebra': {
    vi: {
      summary: 'Nhân ma trận với vectơ, kiểm tra kích thước và tìm hiểu một thành phần PCA giữ lại hay loại bỏ thông tin gì.',
      steps: [
        'Dùng bốn điểm X trong ví dụ, w=[2,-1], b=1. Tính tay Xw+b và ghi kích thước (shape) dự kiến trước khi viết mã NumPy.',
        'Viết affine bằng X @ w + b. Từ chối trọng số sai kích thước và dữ liệu không hữu hạn; in kích thước của X, w và kết quả.',
        'Trừ trung bình của từng đặc trưng, dùng np.linalg.svd rồi chọn hàng đầu của Vt. Chiếu dữ liệu lên trục đó và tái tạo về không gian ban đầu.',
        'Tính tỷ lệ phương sai giữ lại từ bình phương các giá trị kỳ dị (singular value). Vẽ điểm gốc, điểm tái tạo và đoạn nối giữa chúng; nêu rõ thông tin đã mất.',
        'Kiểm tra rằng dùng đủ hai thành phần sẽ tái tạo được dữ liệu và khôi phục được phép dịch. Với dữ liệu hằng, cần nói rõ không có phương sai để giải thích. Không yêu cầu trục SVD có một dấu cố định.',
      ],
      checks: ['Xw+b = [-2,-4,6,4], kích thước (4,).',
        'PCA một thành phần cho scores kích thước (4,1), giữ 80% phương sai và có tổng bình phương sai số=4.',
        'Giải thích được vì sao mất biến thiên theo chiều dọc và vì sao phương sai giữ lại không phải độ chính xác của mô hình.'],
      hints: ['Ma trận (n,d) nhân vectơ (d,) trả vectơ (n,).',
        'Khôi phục bằng scores @ axes + mean; đừng quên mean.'],
      example: 'X = [[-2, -1], [-2, 1], [2, -1], [2, 1]]\nw = [2, -1]\nb = 1',
    },
    en: {
      summary: 'Compute matrix-vector products, inspect shapes and show which information one PCA component discards.',
      steps: [
        'Use the four points below, w=[2,-1] and b=1. Calculate Xw+b by hand and record expected shapes before writing NumPy.',
        'Implement affine with X @ w + b. Reject wrong-shaped weights and non-finite values; print input and output shapes.',
        'Subtract feature means, call np.linalg.svd and select the first row of Vt. Project onto that axis and reconstruct in the original space.',
        'Calculate explained variance from squared singular values. Plot original points, reconstructed points and connecting segments; describe the lost information.',
        'Check full-component reconstruction, translation restoration and rejection of constant data. Do not require fixed SVD axis signs.',
      ],
      checks: ['Xw+b = [-2,-4,6,4] with shape (4,).',
        'One PCA component produces (4,1) scores, retains 80% variance and has squared error 4.',
        'Explain lost vertical variation and why retained variance is not model accuracy.'],
      hints: ['An (n,d) matrix times a (d,) vector returns an (n,) vector.',
        'Reconstruct with scores @ axes + mean; restore the mean.'],
      example: 'X = [[-2, -1], [-2, 1], [2, -1], [2, 1]]\nw = [2, -1]\nb = 1',
    },
  },
  'exercise-2-calculus': {
    vi: {
      summary: 'Đối chiếu gradient tính tay, sai phân hữu hạn (finite difference) và đạo hàm tự động (autograd). Thử các tốc độ học để quan sát hội tụ hoặc phân kỳ.',
      steps: [
        'Chọn L(w)=(w−3)². Tính tay đạo hàm tại 0, 3 và 5; dự đoán chiều cập nhật khi trừ gradient.',
        'Viết hàm mất mát, gradient và sai phân trung tâm với epsilon=1e−5. So sánh trong ngưỡng sai số cho phép, không yêu cầu hai số thực bằng nhau tuyệt đối.',
        'Tạo tensor PyTorch float64 có requires_grad=True, tính cùng hàm mất mát rồi lấy torch.autograd.grad. Đối chiếu cả ba cách tại nhiều điểm.',
        'Từ w=0, chạy 12 bước với tốc độ học (learning rate) 0.1, 0.5, 1 và 1.1. Lưu giá trị hàm mất mát trước cập nhật và sau mỗi bước.',
        'Vẽ hàm mất mát theo w và theo số bước. Dùng e_next=(1−2η)e để giải thích hội tụ, dao động và phân kỳ; chỉ kết luận cho hàm đang xét.',
      ],
      checks: ['Gradient tại 0, 3, 5 lần lượt là -6, 0, 4.',
        'Tốc độ học 0.5 đưa tới w=3 trong một bước; 1 làm w dao động 0↔6; 1.1 làm giá trị hàm mất mát tăng.',
        'Ba cách tính khớp trong ngưỡng sai số cho phép và có ảnh gradient.png.'],
      hints: ['Áp dụng quy tắc đạo hàm hàm hợp (chain rule) cho bình phương.', 'Autograd cần giữ phép tính trên tensor, không chuyển sang .item() trước khi đạo hàm.'],
      example: 'L(w) = (w - 3)^2\ndL/dw = 2 * (w - 3)\nw_next = w - learning_rate * dL/dw',
    },
    en: {
      summary: 'Compare hand, finite-difference and autograd derivatives, then test convergent and divergent learning rates.',
      steps: [
        'Use L(w)=(w−3)². Calculate derivatives at 0, 3 and 5 and predict the direction of a gradient-descent update.',
        'Write loss, gradient and a central difference with epsilon=1e−5. Compare using a tolerance, not exact float equality.',
        'Create a PyTorch float64 tensor with requires_grad=True and differentiate the same loss with torch.autograd.grad. Compare all three at several points.',
        'Start at w=0 and run 12 steps at rates 0.1, 0.5, 1 and 1.1. Record the initial loss and each post-update loss.',
        'Plot loss against w and step. Use e_next=(1−2η)e to explain convergence, oscillation and divergence for this specific function.',
      ],
      checks: ['Gradients at 0, 3 and 5 are -6, 0 and 4.',
        'Rate 0.5 reaches w=3 in one step; rate 1 oscillates 0↔6; rate 1.1 increases loss.',
        'All derivative methods agree within tolerance and gradient.png is produced.'],
      hints: ['Apply the chain rule to the square.', 'Keep tensor operations in autograd; do not call .item() before differentiating.'],
      example: 'L(w) = (w - 3)^2\ndL/dw = 2 * (w - 3)\nw_next = w - learning_rate * dL/dw',
    },
  },
  'exercise-2-probability': {
    vi: {
      summary: 'Mô phỏng Bernoulli, đọc biểu đồ tần suất và phân biệt precision, recall với nhiễu do lấy mẫu.',
      steps: [
        'Ghi giả định các lần thử độc lập, cùng p=0.2. Tính E[X], Var(X) và phương sai của trung bình mẫu trước khi mô phỏng.',
        'Dùng bộ sinh số ngẫu nhiên NumPy với seed cố định để sinh n=20, 200, 20000 giá trị Bernoulli. In trung bình và phương sai với ddof=0.',
        'Vẽ ba biểu đồ tần suất với các khoảng [-0.5,0.5,1.5], trọng số 1/n và cùng thang trục. So sánh tỷ lệ, không so số đếm thô giữa các n.',
        'Từ TP=80, FN=20, FP=90, TN=810, tính tỷ lệ dương thực (prevalence), recall và precision. Viết rõ điều kiện sau dấu | ở từng xác suất.',
        'Kiểm thử p=0/1, đầu vào sai và mẫu số bằng 0. Đổi seed để quan sát nhiễu; không kết luận rằng cứ tăng n là kết quả sẽ gần kỳ vọng hơn.',
      ],
      checks: ['E[X]=0.2 và Var(X)=0.16; trung bình mẫu là giá trị quan sát, không bắt buộc bằng 0.2.',
        'Recall=0.8; precision=80/170≈0.471; tỷ lệ không xác định trả None.',
        'Ảnh histogram.png có cùng trục tỷ lệ cho cả ba mẫu.'],
      hints: ['Precision có mẫu số TP+FP; recall có mẫu số TP+FN.', 'ddof=0 dùng mẫu số n, ddof=1 dùng n−1.'],
      example: 'TP=80, FN=20, FP=90, TN=810\nP(predicted=1 | actual=1) = 80 / 100\nP(actual=1 | predicted=1) = 80 / 170',
    },
    en: {
      summary: 'Simulate Bernoulli samples, compare histograms and distinguish precision, recall and sampling noise.',
      steps: [
        'State independent-trial assumptions and p=0.2. Calculate E[X], Var(X) and variance of the sample mean before simulation.',
        'Use a seeded NumPy RNG to generate 20, 200 and 20000 Bernoulli outcomes. Print the mean and variance with ddof=0.',
        'Plot histograms with bins [-0.5,0.5,1.5], weights 1/n and shared axis scales. Compare fractions instead of raw counts across sample sizes.',
        'From TP=80, FN=20, FP=90 and TN=810, calculate prevalence, recall and precision. Write the condition after | for each probability.',
        'Test p=0/1, invalid inputs and zero denominators. Change the seed to inspect noise without claiming every increase in n moves closer to the expectation.',
      ],
      checks: ['E[X]=0.2 and Var(X)=0.16; observed sample means need not equal 0.2.',
        'Recall=0.8; precision=80/170≈0.471; undefined ratios return None.',
        'histogram.png uses the same fraction scale for all samples.'],
      hints: ['Precision divides by TP+FP; recall divides by TP+FN.', 'ddof=0 divides by n; ddof=1 divides by n−1.'],
      example: 'TP=80, FN=20, FP=90, TN=810\nP(predicted=1 | actual=1) = 80 / 100\nP(actual=1 | predicted=1) = 80 / 170',
    },
  },
  'exercise-2-optimization': {
    vi: {
      summary: 'Tự viết hồi quy tuyến tính rồi so sánh SGD, momentum và Adam qua đường mất mát trên tập huấn luyện và tập kiểm định.',
      steps: [
        'Sinh dữ liệu x∈[-1,1], y=2x+1+noise với seed cố định. Tách tập huấn luyện (train) và kiểm định (validation) trước khi huấn luyện; chọn MSE vì biến cần dự đoán là số liên tục.',
        'Khởi tạo w=b=0, tính gradient mỗi mẫu là 2(wx+b−y)[x,1]. Xáo trộn tập huấn luyện ở mỗi lượt (epoch) bằng bộ sinh số ngẫu nhiên cố định; tuyệt đối không cập nhật tham số bằng tập kiểm định.',
        'Cài đặt SGD, momentum với beta=0.9 và Adam với beta1=0.9, beta2=0.999, epsilon=1e−8. Hiệu chỉnh độ chệch của Adam theo số lần cập nhật trên từng mẫu.',
        'Chạy 40 epoch: tốc độ học của SGD là 0.03, momentum/Adam là 0.003. Thêm SGD với tốc độ học 1e−5 và 2 để quan sát học chậm và tham số tăng mất kiểm soát. Ghi lại mọi cấu hình.',
        'Vẽ MSE trên tập huấn luyện và kiểm định từ epoch 0. Giải thích dấu hiệu thiếu khớp (underfit), quá khớp (overfit) và tối ưu không ổn định. Kiểm thử rằng thay đổi tập kiểm định không làm đổi tham số đã học.',
      ],
      checks: ['Ba cấu hình ổn định học được w gần 2, b gần 1 và MSE trên tập kiểm định dưới 0.03 với dữ liệu của seed này.',
        'Tốc độ học nhỏ khiến mô hình chưa học đủ; tốc độ học 2 bị dừng với thông báo exploding update.',
        'Đường kiểm định được theo dõi riêng; không gọi tập này là tập kiểm tra cuối cùng (test set) hoặc dùng ví dụ để xếp hạng các bộ tối ưu.'],
      hints: ['Giữ momentum/moment qua các bước; không đặt lại về 0 sau mỗi mẫu.',
        'Adam có bộ đếm t từ 1, không dùng số epoch thay cho số lần cập nhật.'],
      example: 'prediction = w * x + b\nerror = prediction - y\ngradient = 2 * error * [x, 1]\nparameters -= learning_rate * update',
    },
    en: {
      summary: 'Implement linear regression and compare SGD, momentum and Adam using train/validation loss curves.',
      steps: [
        'Generate seeded x∈[-1,1] and y=2x+1+noise. Split train/validation before fitting and choose MSE for the continuous target.',
        'Start at w=b=0 with sample gradient 2(wx+b−y)[x,1]. Shuffle training data each epoch with a seeded RNG; never update on validation.',
        'Implement SGD, momentum with beta=0.9 and Adam with beta1=0.9, beta2=0.999 and epsilon=1e−8. Bias-correct Adam by sample update count.',
        'Run 40 epochs: SGD rate 0.03 and momentum/Adam 0.003. Add SGD rates 1e−5 and 2 to inspect slow learning and exploding updates; record configurations.',
        'Plot train/validation MSE from epoch zero. Explain underfitting, overfitting and unstable optimization; test that changing validation labels does not affect fitted parameters.',
      ],
      checks: ['The three stable configurations learn w near 2 and b near 1, with validation MSE below 0.03 on this seeded dataset.',
        'The tiny rate undertrains; rate 2 stops with an exploding-update message.',
        'Validation stays separate; this is neither a final test set nor an optimizer benchmark.'],
      hints: ['Preserve momentum/moments across samples instead of resetting them.',
        'Adam starts its update counter at 1; use sample updates, not epochs.'],
      example: 'prediction = w * x + b\nerror = prediction - y\ngradient = 2 * error * [x, 1]\nparameters -= learning_rate * update',
    },
  },
}
